#!/usr/bin/sh
cmd='git grep -lP'
fcmd=''
gcmd='git grep -P -A 3 -B 3'
space=' '

# In grp (git grep)
# grp "r\\\k" and grp "r\\\\k" can search "r\k"
# grp -P "r\\\\\w" and grp "r\\\\\\k" can search "r\[any charater]"
# grp -P "Color\\\\\\s" and grp -P "Color\\\\\s" can search "Color\[carriage-return character]"
# Only grp -P "Color\\\\" can search "Color\"
for i; do
    # arg="${i//\/\\}"
    arg=$(printf "%q" "$i")
    fcmd=$cmd$space'"'$arg'" | xargs.exe -r '$fcmd
    gcmd=$gcmd" -e \""$arg"\" --or"
done
# fcmd=${fcmd/% | xargs.exe -r /}
gcmd=${gcmd/%--or/}
printf "%s\n" "$fcmd"
printf "%s\n" "$gcmd"

bash -c "$fcmd $gcmd"
exit;

#
# please use single quote e.g. 'Pattern'
# If need backslash in pattern, use backslash to escape. 'Color\' -> 'Color\\'
#git grep -iP --files-with-matches "$1" | xargs.exe git grep -iP --files-with-matches "$2" | xargs.exe git grep -iP -e "$2" --or -e "$1"
#exit;

# Check last char is backslash, then escape. "Color" -> "Color", "Color\\" -> "Color\\"
string=$1
arg1="${string/%\\/\\\\}"
string=$2
arg2="${string/%\\/\\\\}"
git grep -iP --files-with-matches "$arg1" | xargs.exe -r git grep -iP --files-with-matches "$arg2" | xargs.exe -r git grep -iP -e "$arg1" --or -e "$arg2"
exit;

# "using\sSystem" -> "using\\sSystem"
string=$1
arg1="${string/\\/\\\\}";
string=$2
arg2="${string/\\/\\\\}"
git grep -iP --files-with-matches "$arg1" | xargs.exe git grep -iP --files-with-matches "$arg2" | xargs.exe git grep -iP -e "$arg1" --or -e "$arg2"
