#!/usr/bin/sh
# please use single quote e.g. 'Pattern'
# If need backslash in pattern, use backslash to escape. 'Color\' -> 'Color\\'
#git grep -iP --files-with-matches "$1" | xargs.exe git grep -iP --files-with-matches "$2" | xargs.exe git grep -iP -e "$2" --or -e "$1"
#exit;

# Check last char is backslash, then escape. "Color" -> "Color", "Color\\" -> "Color\\"
string=$1
arg1="${string/%\\/\\\\}"
string=$2
arg2="${string/%\\/\\\\}"
git grep -iP --files-with-matches "$arg1" | xargs.exe git grep -iP --files-with-matches "$arg2" | xargs.exe git grep -iP -e "$arg1" --or -e "$arg2"
exit;

string="${string%\}\"
arg1="${string/\\/\\\\}";=
string=$2
arg2="${string/\\/\\\\}"
# "using\sSystem" -> "using\\System"
git grep -iP --files-with-matches "$arg1" | xargs.exe git grep -iP --files-with-matches "$arg2" | xargs.exe git grep -iP -e "$arg1" --or -e "$arg2"
